# Homework Starter — Stage 03: Python Fundamentals

## Instructions
Fill in the cells below to complete your homework. Refer to lecture examples.

In [1]:
# --- packages this notebook needs (uncomment and run once, then re-comment) ---
# !pip install numpy
# !pip install pandas
# !pip install matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. NumPy Operations

In [3]:
# TODO: Create a NumPy array and perform vectorized operations
arr=np.array([1,2,3,4])
print(arr+3)
print(arr*7)
print(arr**2)

[4 5 6 7]
[ 7 14 21 28]
[ 1  4  9 16]


## 2. Compare Loop vs Vectorization

In [4]:
# TODO: Compare speed using %timeit
arr2=np.arange(10000)
%timeit [x**2 for x in arr2]
%timeit arr2**2

339 μs ± 2.98 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.67 μs ± 23.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## 3. Load and Inspect Dataset

In [5]:
# TODO: Load CSV and inspect with .head(), .info(), .describe()
from pathlib import Path
ROOT = Path.cwd().parent
data_path = ROOT/'data'/'raw'/'starter_data.csv'
df = pd.read_csv(data_path)

df.head()

,category,value,date
0,A,10,2025-08-01
1,B,15,2025-08-02
2,A,12,2025-08-03
3,B,18,2025-08-04
4,C,25,2025-08-05


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   category  10 non-null     object
 1   value     10 non-null     int64 
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes


In [7]:
df.describe()

,value
count,10.000000
mean,17.600000
std,7.381659
min,10.000000
25%,12.250000
50%,14.500000
75%,23.250000
max,30.000000


## 4. Summary Statistics and Groupby

In [8]:
# TODO: Perform groupby and save output to data/processed/
df_group = df.groupby('category')['value'].agg(['sum','mean','count'])
save_path = ROOT/'data'/'processed'/'groupsummary.csv'
df_group.to_csv(save_path)

## 5.Reusable Function

In [9]:
import sys
sys.path.insert(0,str(ROOT))

from src.utils import get_category_summary
summary = get_category_summary(df)
print(summary)

          sum       mean  count
category                       
A          46  11.500000      4
B          47  15.666667      3
C          83  27.666667      3
